# my global config
global:
  scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

# Alertmanager configuration
alerting:
  alertmanagers:
  - static_configs:
    - targets:
       - localhost:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  - "rules.yml"
  # - "second_rules.yml"


# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'prometheus'

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.


    static_configs:
    - targets: ['localhost:9090']

  - job_name: 'black_box'
    metrics_path: /probe
    scrape_interval: 5s
    params:
      module: [http_2xx]  # Look for a HTTP 200 response.
    static_configs:
      - targets:
        - http://prometheus.io    # Target to probe with http.
        - https://google.com    # Target to probe with http.
        - http://lsa.jiazhengdev.tw    # Target to probe with http.
        - http://failover-sgp.jiazhengdev.tw
        - http://failover-us.jiazhengdev.tw
        - http://lsalb-d596176d69ccaeb9.elb.us-west-1.amazonaws.com/ # aws-lb
        - http://do-float-ip.jiazhengdev.tw
        - http://do-keepalived-master.jiazhengdev.tw/
        - http://do-keepalived-backup.jiazhengdev.tw/
        - http://do-nginx-primary.jiazhengdev.tw/
        - http://do-nginx-secondary.jiazhengdev.tw/
        - http://aws-us1.jiazhengdev.tw/
        - http://aws-us2.jiazhengdev.tw/
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 127.0.0.1:9115  # The blackbox exporter's real hostname:port.

